version: '3.8'

services:
  api:
    image: node:22-alpine
    container_name: nest-api
    working_dir: /app
    command: sh -c "npm install && npm run dev:api"
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    user: '${MY_UID:-1000}:${MY_GID:-1000}'
    mem_limit: 1g
    cpus: 0.125

  worker:
    image: node:22-alpine
    container_name: nest-worker
    working_dir: /app
    command: sh -c "npm install && npm run dev:worker"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    user: '${MY_UID:-1000}:${MY_GID:-1000}'
    mem_limit: 1g
    cpus: 0.125

  frontend:
    image: node:22-alpine
    container_name: vite-react
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ../boilerplate-crud-vite-react:/app
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    user: '${MY_UID:-1000}:${MY_GID:-1000}'
    mem_limit: 1g
    cpus: 0.125

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=yourpassword
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
